# Generated by Django 5.1 on 2024-08-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='texto',
        ),
    ]
